name: Release
'on':
  workflow_dispatch: null
  push:
    tags:
    - '*'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4.2.2
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Download OpenSSL source
      run: |
        curl -fL -o /tmp/openssl.tar.gz https://github.com/openssl/openssl/releases/download/openssl-3.5.5/openssl-3.5.5.tar.gz
        tar xzf /tmp/openssl.tar.gz -C /tmp
    - name: Checkout BCR
      uses: actions/checkout@v4.2.2
      with:
        repository: illicitonion/bazel-central-registry
        token: ${{ secrets.BCR_GITHUB_TOKEN }}
        path: bazel-central-registry
        ref: refs/heads/main
    - run: git config --global user.email "github@raccoons.build" && git config --global user.name "Raccoons Build"
    - run: (cd bazel-central-registry && git remote add upstream https://github.com/bazelbuild/bazel-central-registry.git && git fetch upstream && git reset --hard upstream/main)
    - run: ./download-buildifier.sh
    - run: >
        python3 generate_constants.py
        --openssl_source_dir=/tmp/openssl-3.5.5
        --output_dir=/tmp/overlay
        --bcr_dir=$(pwd)/bazel-central-registry
        --tag=${{github.ref_name}}
        --buildifier=/tmp/buildifier.exe
        --source_archive=/tmp/openssl.tar.gz
    - run: tar czf bcr.tar.gz bazel-central-registry
    - name: Upload bcr
      uses: actions/upload-artifact@v4
      with:
        name: bcr.tar.gz
        path: bcr.tar.gz
        if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    needs:
      - generate
    steps:
      - name: Download bcr
        uses: actions/download-artifact@v4
        with:
          name: bcr.tar.gz
          path: /tmp/
      - run: tar xzf /tmp/bcr.tar.gz
      - run: git config --global user.email "github@raccoons.build" && git config --global user.name "Raccoons Build"
      - run: cd bazel-central-registry && git checkout -b prep-${{github.ref_name}} && git add . && git commit -m "Release openssl ${{github.ref_name}}" && git push -u origin prep-${{github.ref_name}} && gh pr create --title "Add openssl ${{github.ref_name}}" --body "" --repo bazelbuild/bazel-central-registry
        env:
          GITHUB_TOKEN: ${{ secrets.BCR_GITHUB_TOKEN }}
